version: "3.8"
services:
  chat_api:
    image: srdjankljajo/chat_api
    deploy:
     replicas: 2
     restart_policy:
      condition: any
     update_config:
      parallelism: 2
      delay: 15s 
    build:
     context: .
    ports:
      - 3000:3000 
    networks:
      - websmart

networks:
  websmart:       